services:
  # Основная база данных c 
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-dastarhan}
    ports:
      - "5432:5432"

  # Redis для очередей и кэша
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  # Твой Backend (NestJS)
  backend:
    build: 
      context: ./apps/backend
    depends_on:
      - postgres
      - redis
    environment:
      # Передаем именно те ключи, которые ищет твой код:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: ${DB_USER:-user}
      DATABASE_PASSWORD: ${DB_PASSWORD:-password}
      DATABASE_NAME: ${DB_NAME:-dastarhan}
      # Redis тоже подправь для надежности
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8080:3001"

  # Твой Frontend (Next.js)
  frontend:
    build:
      context: ./apps/frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://backend:3000
